/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/common-api';
export * from './apis/location-api';
export * from './apis/odhactivity-poi-api';
export * from './apis/odhtag-api';
export * from './apis/tag-api';
export * from './apis/weather-api';
export * from './apis/webcam-info-api';

