/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccoDetail
 */
export interface AccoDetail {
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    NameAddition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Street?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Zip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Mobile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Fax?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Firstname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Lastname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    City?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Shortdesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Longdesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    Vat?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoDetail
     */
    CountryCode?: string | null;
}
