/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccoBookingChannel
 */
export interface AccoBookingChannel {
    /**
     * 
     * @type {string}
     * @memberof AccoBookingChannel
     */
    Id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoBookingChannel
     */
    Pos1ID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoBookingChannel
     */
    Portalname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoBookingChannel
     */
    BookingId?: string | null;
}
