/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccoFeatureLinked
 */
export interface AccoFeatureLinked {
    /**
     * 
     * @type {string}
     * @memberof AccoFeatureLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoFeatureLinked
     */
    Id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoFeatureLinked
     */
    Name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoFeatureLinked
     */
    HgvId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccoFeatureLinked
     */
    OtaCodes?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof AccoFeatureLinked
     */
    RoomAmenityCodes?: Array<number> | null;
}
