/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccoFeatureLinked } from './acco-feature-linked';
import { AccoRoomDetail } from './acco-room-detail';
import { ImageGallery } from './image-gallery';
import { LicenseInfo } from './license-info';
import { Metadata } from './metadata';
/**
 * 
 * @export
 * @interface AccommodationRoomLinked
 */
export interface AccommodationRoomLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof AccommodationRoomLinked
     */
    Meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof AccommodationRoomLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {Array<AccoFeatureLinked>}
     * @memberof AccommodationRoomLinked
     */
    Features?: Array<AccoFeatureLinked> | null;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof AccommodationRoomLinked
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof AccommodationRoomLinked
     */
    Id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationRoomLinked
     */
    Shortname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationRoomLinked
     */
    A0RID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationRoomLinked
     */
    Roomtype?: string | null;
    /**
     * 
     * @type {{ [key: string]: AccoRoomDetail; }}
     * @memberof AccommodationRoomLinked
     */
    AccoRoomDetail?: { [key: string]: AccoRoomDetail; } | null;
    /**
     * 
     * @type {Array<ImageGallery>}
     * @memberof AccommodationRoomLinked
     */
    ImageGallery?: Array<ImageGallery> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationRoomLinked
     */
    HasLanguage?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationRoomLinked
     */
    LTSId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationRoomLinked
     */
    HGVId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationRoomLinked
     */
    Source?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationRoomLinked
     */
    RoomCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AccommodationRoomLinked
     */
    Roommax?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AccommodationRoomLinked
     */
    Roommin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AccommodationRoomLinked
     */
    Roomstd?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AccommodationRoomLinked
     */
    PriceFrom?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AccommodationRoomLinked
     */
    RoomQuantity?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationRoomLinked
     */
    RoomNumbers?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof AccommodationRoomLinked
     */
    RoomClassificationCodes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AccommodationRoomLinked
     */
    RoomtypeInt?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof AccommodationRoomLinked
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AccommodationRoomLinked
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationRoomLinked
     */
    PublishedOn?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof AccommodationRoomLinked
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
}
