/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccoBadges } from './acco-badges';
import { AccoBoards } from './acco-boards';
import { AccoBookingChannel } from './acco-booking-channel';
import { AccoCategory } from './acco-category';
import { AccoDetail } from './acco-detail';
import { AccoFeatureLinked } from './acco-feature-linked';
import { AccoRoomInfoLinked } from './acco-room-info-linked';
import { AccoSpecialFeatures } from './acco-special-features';
import { AccoThemes } from './acco-themes';
import { AccoType } from './acco-type';
import { DistanceInfo } from './distance-info';
import { GpsInfo } from './gps-info';
import { ImageGallery } from './image-gallery';
import { IndependentData } from './independent-data';
import { LicenseInfo } from './license-info';
import { LocationInfoLinked } from './location-info-linked';
import { Metadata } from './metadata';
import { MssResponseShort } from './mss-response-short';
import { ODHTags } from './odhtags';
/**
 * 
 * @export
 * @interface AccommodationLinked
 */
export interface AccommodationLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof AccommodationLinked
     */
    Meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    OdhActive?: boolean;
    /**
     * 
     * @type {Array<ODHTags>}
     * @memberof AccommodationLinked
     */
    ODHTags?: Array<ODHTags> | null;
    /**
     * 
     * @type {AccoType}
     * @memberof AccommodationLinked
     */
    AccoType?: AccoType;
    /**
     * 
     * @type {AccoCategory}
     * @memberof AccommodationLinked
     */
    AccoCategory?: AccoCategory;
    /**
     * 
     * @type {Array<AccoBoards>}
     * @memberof AccommodationLinked
     */
    AccoBoards?: Array<AccoBoards> | null;
    /**
     * 
     * @type {Array<AccoBadges>}
     * @memberof AccommodationLinked
     */
    AccoBadges?: Array<AccoBadges> | null;
    /**
     * 
     * @type {Array<AccoThemes>}
     * @memberof AccommodationLinked
     */
    AccoThemes?: Array<AccoThemes> | null;
    /**
     * 
     * @type {Array<AccoSpecialFeatures>}
     * @memberof AccommodationLinked
     */
    AccoSpecialFeatures?: Array<AccoSpecialFeatures> | null;
    /**
     * 
     * @type {Array<AccoFeatureLinked>}
     * @memberof AccommodationLinked
     */
    Features?: Array<AccoFeatureLinked> | null;
    /**
     * 
     * @type {Array<AccoRoomInfoLinked>}
     * @memberof AccommodationLinked
     */
    AccoRoomInfo?: Array<AccoRoomInfoLinked> | null;
    /**
     * 
     * @type {LocationInfoLinked}
     * @memberof AccommodationLinked
     */
    LocationInfo?: LocationInfoLinked;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof AccommodationLinked
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    Id?: string | null;
    /**
     * Data is marked as Active by the data provider
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    Active?: boolean;
    /**
     * Accommodation ID on the HGV System, use Mapping instead
     * @type {string}
     * @memberof AccommodationLinked
     */
    HgvId?: string | null;
    /**
     * Use AccoDetail.lang.Name
     * @type {string}
     * @memberof AccommodationLinked
     */
    Shortname?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLinked
     */
    Representation?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    HasApartment?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    HasRoom?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    IsCamping?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    IsGastronomy?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    IsBookable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    IsAccommodation?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    SmgActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    TVMember?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    TourismVereinId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    MainLanguage?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AccommodationLinked
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AccommodationLinked
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    Gpstype?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLinked
     */
    Latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLinked
     */
    Longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof AccommodationLinked
     */
    Altitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    AltitudeUnitofMeasure?: string | null;
    /**
     * 
     * @type {DistanceInfo}
     * @memberof AccommodationLinked
     */
    DistanceInfo?: DistanceInfo;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    AccoCategoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    AccoTypeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    DistrictId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationLinked
     */
    BoardIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationLinked
     */
    MarketingGroupIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationLinked
     */
    BadgeIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationLinked
     */
    ThemeIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationLinked
     */
    SpecialFeaturesIds?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: AccoDetail; }}
     * @memberof AccommodationLinked
     */
    AccoDetail?: { [key: string]: AccoDetail; } | null;
    /**
     * 
     * @type {Array<AccoBookingChannel>}
     * @memberof AccommodationLinked
     */
    AccoBookingChannel?: Array<AccoBookingChannel> | null;
    /**
     * 
     * @type {Array<ImageGallery>}
     * @memberof AccommodationLinked
     */
    ImageGallery?: Array<ImageGallery> | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    GastronomyId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationLinked
     */
    SmgTags?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationLinked
     */
    HasLanguage?: Array<string> | null;
    /**
     * 
     * @type {Array<MssResponseShort>}
     * @memberof AccommodationLinked
     */
    MssResponseShort?: Array<MssResponseShort> | null;
    /**
     * 
     * @type {IndependentData}
     * @memberof AccommodationLinked
     */
    IndependentData?: IndependentData;
    /**
     * generated field
     * @type {{ [key: string]: GpsInfo; }}
     * @memberof AccommodationLinked
     */
    GpsPoints?: { [key: string]: GpsInfo; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccommodationLinked
     */
    PublishedOn?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationLinked
     */
    Source?: string | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof AccommodationLinked
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * Accommodation Id on Trust You
     * @type {string}
     * @memberof AccommodationLinked
     */
    TrustYouID?: string | null;
    /**
     * Review Score on Trust You
     * @type {number}
     * @memberof AccommodationLinked
     */
    TrustYouScore?: number;
    /**
     * Number of Ratings in Trust You
     * @type {number}
     * @memberof AccommodationLinked
     */
    TrustYouResults?: number;
    /**
     * Active in Trust You
     * @type {boolean}
     * @memberof AccommodationLinked
     */
    TrustYouActive?: boolean;
    /**
     * Trust You State on LTS
     * @type {number}
     * @memberof AccommodationLinked
     */
    TrustYouState?: number;
}
