/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AdditionalPoiInfos
 */
export interface AdditionalPoiInfos {
    /**
     * 
     * @type {string}
     * @memberof AdditionalPoiInfos
     */
    Novelty?: string | null;
    /**
     * Use Categories instead
     * @type {string}
     * @memberof AdditionalPoiInfos
     */
    MainType?: string | null;
    /**
     * Use Categories instead
     * @type {string}
     * @memberof AdditionalPoiInfos
     */
    SubType?: string | null;
    /**
     * Use Categories instead
     * @type {string}
     * @memberof AdditionalPoiInfos
     */
    PoiType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdditionalPoiInfos
     */
    Language?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdditionalPoiInfos
     */
    Categories?: Array<string> | null;
}
