/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContactInfos } from './contact-infos';
/**
 * 
 * @export
 * @interface AdditionalContact
 */
export interface AdditionalContact {
    /**
     * 
     * @type {string}
     * @memberof AdditionalContact
     */
    Type?: string | null;
    /**
     * 
     * @type {ContactInfos}
     * @memberof AdditionalContact
     */
    ContactInfos?: ContactInfos;
    /**
     * 
     * @type {string}
     * @memberof AdditionalContact
     */
    Description?: string | null;
}
