/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Detail } from './detail';
import { LicenseInfo } from './license-info';
import { Metadata } from './metadata';
import { MunicipalityLink } from './municipality-link';
import { RegionLink } from './region-link';
import { SkiAreaLink } from './ski-area-link';
import { TourismAssociationLink } from './tourism-association-link';
/**
 * 
 * @export
 * @interface AreaLinked
 */
export interface AreaLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof AreaLinked
     */
    Meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AreaLinked
     */
    OdhActive?: boolean;
    /**
     * 
     * @type {RegionLink}
     * @memberof AreaLinked
     */
    Region?: RegionLink;
    /**
     * 
     * @type {MunicipalityLink}
     * @memberof AreaLinked
     */
    Municipality?: MunicipalityLink;
    /**
     * 
     * @type {TourismAssociationLink}
     * @memberof AreaLinked
     */
    Tourismassociation?: TourismAssociationLink;
    /**
     * 
     * @type {SkiAreaLink}
     * @memberof AreaLinked
     */
    SkiArea?: SkiAreaLink;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof AreaLinked
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    Id?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AreaLinked
     */
    Active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AreaLinked
     */
    SmgActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    Shortname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    CustomId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    RegionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    TourismvereinId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    MunicipalityId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    SkiAreaID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    GID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    LtsID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    AreaType?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AreaLinked
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AreaLinked
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof AreaLinked
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {string}
     * @memberof AreaLinked
     */
    Source?: string | null;
    /**
     * 
     * @type {{ [key: string]: Detail; }}
     * @memberof AreaLinked
     */
    Detail?: { [key: string]: Detail; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AreaLinked
     */
    PublishedOn?: Array<string> | null;
}
