/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalArticleInfos } from './additional-article-infos';
import { ArticleLinkInfo } from './article-link-info';
import { ContactInfos } from './contact-infos';
import { Detail } from './detail';
import { DistanceInfo } from './distance-info';
import { GpsInfo } from './gps-info';
import { GpsTrack } from './gps-track';
import { ImageGallery } from './image-gallery';
import { LicenseInfo } from './license-info';
import { Metadata } from './metadata';
import { ODHActivityPoiTypesLink } from './odhactivity-poi-types-link';
import { ODHTags } from './odhtags';
import { OperationSchedule } from './operation-schedule';
/**
 * 
 * @export
 * @interface ArticlesLinked
 */
export interface ArticlesLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof ArticlesLinked
     */
    Meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof ArticlesLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ArticlesLinked
     */
    OdhActive?: boolean;
    /**
     * 
     * @type {Array<ODHActivityPoiTypesLink>}
     * @memberof ArticlesLinked
     */
    ArticleTypes?: Array<ODHActivityPoiTypesLink> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArticlesLinked
     */
    ArticleTypeList?: Array<string> | null;
    /**
     * 
     * @type {Array<ODHTags>}
     * @memberof ArticlesLinked
     */
    ODHTags?: Array<ODHTags> | null;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof ArticlesLinked
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof ArticlesLinked
     */
    Id?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ArticlesLinked
     */
    Active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ArticlesLinked
     */
    Shortname?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ArticlesLinked
     */
    Highlight?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ArticlesLinked
     */
    Type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticlesLinked
     */
    SubType?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ArticlesLinked
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ArticlesLinked
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ArticlesLinked
     */
    SmgActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ArticlesLinked
     */
    ArticleDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ArticlesLinked
     */
    ArticleDateTo?: Date | null;
    /**
     * 
     * @type {Array<OperationSchedule>}
     * @memberof ArticlesLinked
     */
    OperationSchedule?: Array<OperationSchedule> | null;
    /**
     * 
     * @type {Array<GpsInfo>}
     * @memberof ArticlesLinked
     */
    GpsInfo?: Array<GpsInfo> | null;
    /**
     * 
     * @type {Array<GpsTrack>}
     * @memberof ArticlesLinked
     */
    GpsTrack?: Array<GpsTrack> | null;
    /**
     * 
     * @type {Array<ImageGallery>}
     * @memberof ArticlesLinked
     */
    ImageGallery?: Array<ImageGallery> | null;
    /**
     * 
     * @type {{ [key: string]: Detail; }}
     * @memberof ArticlesLinked
     */
    Detail?: { [key: string]: Detail; } | null;
    /**
     * 
     * @type {{ [key: string]: ContactInfos; }}
     * @memberof ArticlesLinked
     */
    ContactInfos?: { [key: string]: ContactInfos; } | null;
    /**
     * 
     * @type {{ [key: string]: AdditionalArticleInfos; }}
     * @memberof ArticlesLinked
     */
    AdditionalArticleInfos?: { [key: string]: AdditionalArticleInfos; } | null;
    /**
     * 
     * @type {{ [key: string]: ArticleLinkInfo; }}
     * @memberof ArticlesLinked
     */
    ArticleLinkInfo?: { [key: string]: ArticleLinkInfo; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArticlesLinked
     */
    SmgTags?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArticlesLinked
     */
    HasLanguage?: Array<string> | null;
    /**
     * 
     * @type {Date}
     * @memberof ArticlesLinked
     */
    ExpirationDate?: Date | null;
    /**
     * generated field
     * @type {{ [key: string]: GpsInfo; }}
     * @memberof ArticlesLinked
     */
    GpsPoints?: { [key: string]: GpsInfo; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArticlesLinked
     */
    PublishedOn?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ArticlesLinked
     */
    Source?: string | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof ArticlesLinked
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {DistanceInfo}
     * @memberof ArticlesLinked
     */
    DistanceInfo?: DistanceInfo;
}
