/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ArticleTypes
 */
export interface ArticleTypes {
    /**
     * 
     * @type {string}
     * @memberof ArticleTypes
     */
    Id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ArticleTypes
     */
    Bitmask?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleTypes
     */
    Type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticleTypes
     */
    Parent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticleTypes
     */
    Key?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ArticleTypes
     */
    TypeDesc?: { [key: string]: string; } | null;
}
