/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BezirksForecast
 */
export interface BezirksForecast {
    /**
     * 
     * @type {Date}
     * @memberof BezirksForecast
     */
    Date?: Date;
    /**
     * 
     * @type {string}
     * @memberof BezirksForecast
     */
    WeatherCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BezirksForecast
     */
    WeatherDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BezirksForecast
     */
    WeatherImgUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    MaxTemp?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    MinTemp?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    Freeze?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    RainFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    RainTo?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    Part1?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    Part2?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    Part3?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    Part4?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    Thunderstorm?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    SymbolId?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    Reliability?: number | null;
}
