/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BezirksForecast
 */
export interface BezirksForecast {
    /**
     * 
     * @type {Date}
     * @memberof BezirksForecast
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof BezirksForecast
     */
    weatherCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BezirksForecast
     */
    weatherDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BezirksForecast
     */
    weatherImgUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    maxTemp?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    minTemp?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    freeze?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    rainFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    rainTo?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    part1?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    part2?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    part3?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    part4?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    thunderstorm?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    symbolId?: number;
    /**
     * 
     * @type {number}
     * @memberof BezirksForecast
     */
    reliability?: number | null;
}
