/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CheapestOffer
 */
export interface CheapestOffer {
    /**
     * 
     * @type {string}
     * @memberof CheapestOffer
     */
    RoomId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CheapestOffer
     */
    RoomSeq?: number;
    /**
     * 
     * @type {number}
     * @memberof CheapestOffer
     */
    Price?: number;
    /**
     * 
     * @type {number}
     * @memberof CheapestOffer
     */
    RoomFree?: number | null;
}
