/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CheapestOffer } from './cheapest-offer';
/**
 * 
 * @export
 * @interface CheapestRoomCombination
 */
export interface CheapestRoomCombination {
    /**
     * 
     * @type {Array<CheapestOffer>}
     * @memberof CheapestRoomCombination
     */
    CheapestRoomCombinationDetail?: Array<CheapestOffer> | null;
    /**
     * 
     * @type {string}
     * @memberof CheapestRoomCombination
     */
    Service?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CheapestRoomCombination
     */
    Price?: number;
}
