/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Conditions
 */
export interface Conditions {
    /**
     * 
     * @type {Date}
     * @memberof Conditions
     */
    Date?: Date;
    /**
     * 
     * @type {string}
     * @memberof Conditions
     */
    Title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Conditions
     */
    WeatherCondition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Conditions
     */
    WeatherImgurl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Conditions
     */
    Temperatures?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Conditions
     */
    Weatherdesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Conditions
     */
    Reliability?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Conditions
     */
    TempMaxmax?: number;
    /**
     * 
     * @type {number}
     * @memberof Conditions
     */
    TempMaxmin?: number;
    /**
     * 
     * @type {number}
     * @memberof Conditions
     */
    TempMinmax?: number;
    /**
     * 
     * @type {number}
     * @memberof Conditions
     */
    TempMinmin?: number;
    /**
     * 
     * @type {number}
     * @memberof Conditions
     */
    BulletinStatus?: number;
}
