/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Detail
 */
export interface Detail {
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    header?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    subHeader?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    introText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    baseText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    additionalText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    metaTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    metaDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    getThereText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    language?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Detail
     */
    keywords?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    parkingInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    publicTransportationInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    authorTip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    safetyInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    equipmentInfo?: string | null;
}
