/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Detail
 */
export interface Detail {
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    Header?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    SubHeader?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    IntroText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    BaseText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    Title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    AdditionalText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    MetaTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    MetaDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    GetThereText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    Language?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Detail
     */
    Keywords?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    ParkingInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    PublicTransportationInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    AuthorTip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    SafetyInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Detail
     */
    EquipmentInfo?: string | null;
}
