/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DishRatesLinked
 */
export interface DishRatesLinked {
    /**
     * 
     * @type {string}
     * @memberof DishRatesLinked
     */
    self?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DishRatesLinked
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DishRatesLinked
     */
    shortname?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DishRatesLinked
     */
    minAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof DishRatesLinked
     */
    maxAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof DishRatesLinked
     */
    currencyCode?: string | null;
}
