/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventBookingDetail } from './event-booking-detail';
/**
 * 
 * @export
 * @interface EventBooking
 */
export interface EventBooking {
    /**
     * 
     * @type {Date}
     * @memberof EventBooking
     */
    BookableFrom?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EventBooking
     */
    BookableTo?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof EventBooking
     */
    AccommodationAssignment?: number | null;
    /**
     * 
     * @type {{ [key: string]: EventBookingDetail; }}
     * @memberof EventBooking
     */
    BookingUrl?: { [key: string]: EventBookingDetail; } | null;
}
