/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventAdditionalInfos
 */
export interface EventAdditionalInfos {
    /**
     * 
     * @type {string}
     * @memberof EventAdditionalInfos
     */
    Mplace?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventAdditionalInfos
     */
    Reg?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventAdditionalInfos
     */
    Location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventAdditionalInfos
     */
    Language?: string | null;
}
