/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventDescAdditional
 */
export interface EventDescAdditional {
    /**
     * 
     * @type {string}
     * @memberof EventDescAdditional
     */
    Type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventDescAdditional
     */
    Language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventDescAdditional
     */
    Order?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventDescAdditional
     */
    RQPlain?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventDescAdditional
     */
    RQHtml?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventDescAdditional
     */
    RSPlain?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventDescAdditional
     */
    RSHtml?: string | null;
}
