/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventDateCalculatedDay
 */
export interface EventDateCalculatedDay {
    /**
     * 
     * @type {string}
     * @memberof EventDateCalculatedDay
     */
    CDayRID?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EventDateCalculatedDay
     */
    Day?: Date;
    /**
     * 
     * @type {string}
     * @memberof EventDateCalculatedDay
     */
    Begin?: string;
}
