/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContactInfos } from './contact-infos';
import { Detail } from './detail';
import { DistanceInfo } from './distance-info';
import { DistrictLink } from './district-link';
import { EventAdditionalInfos } from './event-additional-infos';
import { EventBooking } from './event-booking';
import { EventCrossSelling } from './event-cross-selling';
import { EventDate } from './event-date';
import { EventDescAdditional } from './event-desc-additional';
import { EventOperationScheduleOverview } from './event-operation-schedule-overview';
import { EventPrice } from './event-price';
import { EventPublisher } from './event-publisher';
import { GpsInfo } from './gps-info';
import { ImageGallery } from './image-gallery';
import { LTSTagsLinked } from './ltstags-linked';
import { LicenseInfo } from './license-info';
import { LocationInfoLinked } from './location-info-linked';
import { Metadata } from './metadata';
import { ODHTags } from './odhtags';
import { TopicLinked } from './topic-linked';
/**
 * 
 * @export
 * @interface EventLinked
 */
export interface EventLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof EventLinked
     */
    Meta?: Metadata;
    /**
     * Obsolete
     * @type {Array<Date>}
     * @memberof EventLinked
     */
    EventDatesBegin?: Array<Date> | null;
    /**
     * Obsolete
     * @type {Array<Date>}
     * @memberof EventLinked
     */
    EventDatesEnd?: Array<Date> | null;
    /**
     * Obsolete
     * @type {number}
     * @memberof EventLinked
     */
    EventDateCounter?: number;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {Array<DistrictLink>}
     * @memberof EventLinked
     */
    Districts?: Array<DistrictLink> | null;
    /**
     * 
     * @type {Array<ODHTags>}
     * @memberof EventLinked
     */
    ODHTags?: Array<ODHTags> | null;
    /**
     * 
     * @type {boolean}
     * @memberof EventLinked
     */
    OdhActive?: boolean;
    /**
     * 
     * @type {Array<TopicLinked>}
     * @memberof EventLinked
     */
    Topics?: Array<TopicLinked> | null;
    /**
     * 
     * @type {LocationInfoLinked}
     * @memberof EventLinked
     */
    LocationInfo?: LocationInfoLinked;
    /**
     * 
     * @type {Array<LTSTagsLinked>}
     * @memberof EventLinked
     */
    LTSTags?: Array<LTSTagsLinked> | null;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof EventLinked
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    Id?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EventLinked
     */
    Active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    Shortname?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EventLinked
     */
    DateBegin?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EventLinked
     */
    DateEnd?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EventLinked
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EventLinked
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    Gpstype?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EventLinked
     */
    Latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof EventLinked
     */
    Longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof EventLinked
     */
    Altitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    AltitudeUnitofMeasure?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    OrgRID?: string | null;
    /**
     * Obsolete use EventPublisher List
     * @type {number}
     * @memberof EventLinked
     */
    Ranc?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    Ticket?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    SignOn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    PayMet?: string | null;
    /**
     * Obsolete
     * @type {string}
     * @memberof EventLinked
     */
    Type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    Pdf?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    DistrictId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventLinked
     */
    DistrictIds?: Array<string> | null;
    /**
     * 
     * @type {Array<ImageGallery>}
     * @memberof EventLinked
     */
    ImageGallery?: Array<ImageGallery> | null;
    /**
     * 
     * @type {{ [key: string]: Detail; }}
     * @memberof EventLinked
     */
    Detail?: { [key: string]: Detail; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventLinked
     */
    TopicRIDs?: Array<string> | null;
    /**
     * 
     * @type {Array<EventPublisher>}
     * @memberof EventLinked
     */
    EventPublisher?: Array<EventPublisher> | null;
    /**
     * 
     * @type {{ [key: string]: EventAdditionalInfos; }}
     * @memberof EventLinked
     */
    EventAdditionalInfos?: { [key: string]: EventAdditionalInfos; } | null;
    /**
     * 
     * @type {{ [key: string]: EventPrice; }}
     * @memberof EventLinked
     */
    EventPrice?: { [key: string]: EventPrice; } | null;
    /**
     * 
     * @type {Array<EventDate>}
     * @memberof EventLinked
     */
    EventDate?: Array<EventDate> | null;
    /**
     * 
     * @type {{ [key: string]: ContactInfos; }}
     * @memberof EventLinked
     */
    ContactInfos?: { [key: string]: ContactInfos; } | null;
    /**
     * 
     * @type {{ [key: string]: ContactInfos; }}
     * @memberof EventLinked
     */
    OrganizerInfos?: { [key: string]: ContactInfos; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventLinked
     */
    SmgTags?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof EventLinked
     */
    SmgActive?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventLinked
     */
    HasLanguage?: Array<string> | null;
    /**
     * 
     * @type {Date}
     * @memberof EventLinked
     */
    NextBeginDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    Source?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EventLinked
     */
    GrpEvent?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof EventLinked
     */
    EventBenefit?: boolean | null;
    /**
     * 
     * @type {EventBooking}
     * @memberof EventLinked
     */
    EventBooking?: EventBooking;
    /**
     * 
     * @type {{ [key: string]: Array<EventPrice>; }}
     * @memberof EventLinked
     */
    EventPrices?: { [key: string]: Array<EventPrice>; } | null;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof EventLinked
     */
    Hashtag?: { [key: string]: Array<string>; } | null;
    /**
     * 
     * @type {EventOperationScheduleOverview}
     * @memberof EventLinked
     */
    EventOperationScheduleOverview?: EventOperationScheduleOverview;
    /**
     * generated field
     * @type {{ [key: string]: GpsInfo; }}
     * @memberof EventLinked
     */
    GpsPoints?: { [key: string]: GpsInfo; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventLinked
     */
    PublishedOn?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof EventLinked
     */
    ClassificationRID?: string | null;
    /**
     * 
     * @type {Array<EventCrossSelling>}
     * @memberof EventLinked
     */
    EventCrossSelling?: Array<EventCrossSelling> | null;
    /**
     * 
     * @type {{ [key: string]: EventDescAdditional; }}
     * @memberof EventLinked
     */
    EventDescAdditional?: { [key: string]: EventDescAdditional; } | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof EventLinked
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {DistanceInfo}
     * @memberof EventLinked
     */
    DistanceInfo?: DistanceInfo;
}
