/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventOperationScheduleOverview
 */
export interface EventOperationScheduleOverview {
    /**
     * 
     * @type {boolean}
     * @memberof EventOperationScheduleOverview
     */
    Monday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EventOperationScheduleOverview
     */
    Tuesday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EventOperationScheduleOverview
     */
    Wednesday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EventOperationScheduleOverview
     */
    Thursday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EventOperationScheduleOverview
     */
    Friday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EventOperationScheduleOverview
     */
    Saturday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EventOperationScheduleOverview
     */
    Sunday?: boolean;
}
