/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Forecast
 */
export interface Forecast {
    /**
     * 
     * @type {Date}
     * @memberof Forecast
     */
    Date?: Date;
    /**
     * 
     * @type {number}
     * @memberof Forecast
     */
    TempMaxmax?: number;
    /**
     * 
     * @type {number}
     * @memberof Forecast
     */
    TempMaxmin?: number;
    /**
     * 
     * @type {number}
     * @memberof Forecast
     */
    TempMinmax?: number;
    /**
     * 
     * @type {number}
     * @memberof Forecast
     */
    TempMinmin?: number;
    /**
     * 
     * @type {string}
     * @memberof Forecast
     */
    Weatherdesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Forecast
     */
    Weathercode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Forecast
     */
    WeatherImgurl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Forecast
     */
    Reliability?: string | null;
}
