/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CapacityCeremonyLinked } from './capacity-ceremony-linked';
import { CategoryCodesLinked } from './category-codes-linked';
import { ContactInfos } from './contact-infos';
import { Detail } from './detail';
import { DishRatesLinked } from './dish-rates-linked';
import { DistanceInfo } from './distance-info';
import { FacilitiesLinked } from './facilities-linked';
import { GpsInfo } from './gps-info';
import { ImageGallery } from './image-gallery';
import { LicenseInfo } from './license-info';
import { LocationInfoLinked } from './location-info-linked';
import { Metadata } from './metadata';
import { ODHTags } from './odhtags';
import { OperationSchedule } from './operation-schedule';
/**
 * 
 * @export
 * @interface GastronomyLinked
 */
export interface GastronomyLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof GastronomyLinked
     */
    Meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof GastronomyLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GastronomyLinked
     */
    OdhActive?: boolean;
    /**
     * 
     * @type {Array<ODHTags>}
     * @memberof GastronomyLinked
     */
    ODHTags?: Array<ODHTags> | null;
    /**
     * 
     * @type {Array<CategoryCodesLinked>}
     * @memberof GastronomyLinked
     */
    CategoryCodes?: Array<CategoryCodesLinked> | null;
    /**
     * 
     * @type {Array<DishRatesLinked>}
     * @memberof GastronomyLinked
     */
    DishRates?: Array<DishRatesLinked> | null;
    /**
     * 
     * @type {Array<CapacityCeremonyLinked>}
     * @memberof GastronomyLinked
     */
    CapacityCeremony?: Array<CapacityCeremonyLinked> | null;
    /**
     * 
     * @type {Array<FacilitiesLinked>}
     * @memberof GastronomyLinked
     */
    Facilities?: Array<FacilitiesLinked> | null;
    /**
     * 
     * @type {LocationInfoLinked}
     * @memberof GastronomyLinked
     */
    LocationInfo?: LocationInfoLinked;
    /**
     * generated field
     * @type {{ [key: string]: GpsInfo; }}
     * @memberof GastronomyLinked
     */
    GpsPoints?: { [key: string]: GpsInfo; } | null;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof GastronomyLinked
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof GastronomyLinked
     */
    Id?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GastronomyLinked
     */
    Active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GastronomyLinked
     */
    Shortname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GastronomyLinked
     */
    Type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GastronomyLinked
     */
    DistrictId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GastronomyLinked
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof GastronomyLinked
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GastronomyLinked
     */
    Gpstype?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GastronomyLinked
     */
    Latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof GastronomyLinked
     */
    Longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof GastronomyLinked
     */
    Altitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GastronomyLinked
     */
    AltitudeUnitofMeasure?: string | null;
    /**
     * 
     * @type {Array<OperationSchedule>}
     * @memberof GastronomyLinked
     */
    OperationSchedule?: Array<OperationSchedule> | null;
    /**
     * 
     * @type {number}
     * @memberof GastronomyLinked
     */
    MaxSeatingCapacity?: number | null;
    /**
     * 
     * @type {Array<ImageGallery>}
     * @memberof GastronomyLinked
     */
    ImageGallery?: Array<ImageGallery> | null;
    /**
     * 
     * @type {{ [key: string]: Detail; }}
     * @memberof GastronomyLinked
     */
    Detail?: { [key: string]: Detail; } | null;
    /**
     * 
     * @type {{ [key: string]: ContactInfos; }}
     * @memberof GastronomyLinked
     */
    ContactInfos?: { [key: string]: ContactInfos; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GastronomyLinked
     */
    MarketinggroupId?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof GastronomyLinked
     */
    AccommodationId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GastronomyLinked
     */
    SmgTags?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof GastronomyLinked
     */
    SmgActive?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GastronomyLinked
     */
    HasLanguage?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof GastronomyLinked
     */
    RepresentationRestriction?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GastronomyLinked
     */
    PublishedOn?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof GastronomyLinked
     */
    Source?: string | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof GastronomyLinked
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {DistanceInfo}
     * @memberof GastronomyLinked
     */
    DistanceInfo?: DistanceInfo;
}
