/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GpsInfo
 */
export interface GpsInfo {
    /**
     * 
     * @type {string}
     * @memberof GpsInfo
     */
    gpstype?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GpsInfo
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof GpsInfo
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof GpsInfo
     */
    altitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GpsInfo
     */
    altitudeUnitofMeasure?: string | null;
}
