/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ImageGallery
 */
export interface ImageGallery {
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    ImageName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    ImageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ImageGallery
     */
    Width?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ImageGallery
     */
    Height?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    ImageSource?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ImageGallery
     */
    ImageTitle?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ImageGallery
     */
    ImageDesc?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ImageGallery
     */
    ImageAltText?: { [key: string]: string; } | null;
    /**
     * 
     * @type {boolean}
     * @memberof ImageGallery
     */
    IsInGallery?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof ImageGallery
     */
    ListPosition?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ImageGallery
     */
    ValidFrom?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ImageGallery
     */
    ValidTo?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    CopyRight?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    License?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageGallery
     */
    LicenseHolder?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ImageGallery
     */
    ImageTags?: Array<string> | null;
}
