/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LicenseInfo
 */
export interface LicenseInfo {
    /**
     * 
     * @type {string}
     * @memberof LicenseInfo
     */
    license?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LicenseInfo
     */
    licenseHolder?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LicenseInfo
     */
    author?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LicenseInfo
     */
    closedData?: boolean;
}
