/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AreaInfo } from './area-info';
import { DistrictInfo } from './district-info';
import { MunicipalityInfo } from './municipality-info';
import { RegionInfo } from './region-info';
import { TvInfo } from './tv-info';
/**
 * 
 * @export
 * @interface LocationInfo
 */
export interface LocationInfo {
    /**
     * 
     * @type {RegionInfo}
     * @memberof LocationInfo
     */
    RegionInfo?: RegionInfo;
    /**
     * 
     * @type {TvInfo}
     * @memberof LocationInfo
     */
    TvInfo?: TvInfo;
    /**
     * 
     * @type {MunicipalityInfo}
     * @memberof LocationInfo
     */
    MunicipalityInfo?: MunicipalityInfo;
    /**
     * 
     * @type {DistrictInfo}
     * @memberof LocationInfo
     */
    DistrictInfo?: DistrictInfo;
    /**
     * 
     * @type {AreaInfo}
     * @memberof LocationInfo
     */
    AreaInfo?: AreaInfo;
}
