/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AreaInfoLinked } from './area-info-linked';
import { DistrictInfoLinked } from './district-info-linked';
import { MunicipalityInfoLinked } from './municipality-info-linked';
import { RegionInfoLinked } from './region-info-linked';
import { TvInfoLinked } from './tv-info-linked';
/**
 * 
 * @export
 * @interface LocationInfoLinked
 */
export interface LocationInfoLinked {
    /**
     * 
     * @type {RegionInfoLinked}
     * @memberof LocationInfoLinked
     */
    RegionInfo?: RegionInfoLinked;
    /**
     * 
     * @type {TvInfoLinked}
     * @memberof LocationInfoLinked
     */
    TvInfo?: TvInfoLinked;
    /**
     * 
     * @type {MunicipalityInfoLinked}
     * @memberof LocationInfoLinked
     */
    MunicipalityInfo?: MunicipalityInfoLinked;
    /**
     * 
     * @type {DistrictInfoLinked}
     * @memberof LocationInfoLinked
     */
    DistrictInfo?: DistrictInfoLinked;
    /**
     * 
     * @type {AreaInfoLinked}
     * @memberof LocationInfoLinked
     */
    AreaInfo?: AreaInfoLinked;
}
