/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LTSTins } from './ltstins';
/**
 * 
 * @export
 * @interface LTSTagsLinked
 */
export interface LTSTagsLinked {
    /**
     * 
     * @type {string}
     * @memberof LTSTagsLinked
     */
    self?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LTSTagsLinked
     */
    id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LTSTagsLinked
     */
    level?: number;
    /**
     * 
     * @type {string}
     * @memberof LTSTagsLinked
     */
    LTSRID?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LTSTagsLinked
     */
    tagName?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<LTSTins>}
     * @memberof LTSTagsLinked
     */
    lTSTins?: Array<LTSTins> | null;
}
