/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DistanceInfo } from './distance-info';
import { GpsInfo } from './gps-info';
import { LicenseInfo } from './license-info';
import { LocationInfo } from './location-info';
import { WeatherObservation } from './weather-observation';
/**
 * 
 * @export
 * @interface Measuringpoint
 */
export interface Measuringpoint {
    /**
     * 
     * @type {LicenseInfo}
     * @memberof Measuringpoint
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof Measuringpoint
     */
    Id?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Measuringpoint
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Measuringpoint
     */
    LastUpdate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Measuringpoint
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof Measuringpoint
     */
    Active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Measuringpoint
     */
    SmgActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Measuringpoint
     */
    Shortname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Measuringpoint
     */
    Gpstype?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Measuringpoint
     */
    Latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof Measuringpoint
     */
    Longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof Measuringpoint
     */
    Altitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Measuringpoint
     */
    AltitudeUnitofMeasure?: string | null;
    /**
     * 
     * @type {DistanceInfo}
     * @memberof Measuringpoint
     */
    DistanceInfo?: DistanceInfo;
    /**
     * 
     * @type {string}
     * @memberof Measuringpoint
     */
    SnowHeight?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Measuringpoint
     */
    newSnowHeight?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Measuringpoint
     */
    Temperature?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Measuringpoint
     */
    LastSnowDate?: Date;
    /**
     * 
     * @type {Array<WeatherObservation>}
     * @memberof Measuringpoint
     */
    WeatherObservation?: Array<WeatherObservation> | null;
    /**
     * 
     * @type {LocationInfo}
     * @memberof Measuringpoint
     */
    LocationInfo?: LocationInfo;
    /**
     * 
     * @type {string}
     * @memberof Measuringpoint
     */
    OwnerId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Measuringpoint
     */
    AreaIds?: Array<string> | null;
    /**
     * generated field
     * @type {{ [key: string]: GpsInfo; }}
     * @memberof Measuringpoint
     */
    GpsPoints?: { [key: string]: GpsInfo; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Measuringpoint
     */
    PublishedOn?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof Measuringpoint
     */
    Source?: string | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof Measuringpoint
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Measuringpoint
     */
    SkiAreaIds?: Array<string> | null;
}
