/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalContact } from './additional-contact';
import { AdditionalPoiInfos } from './additional-poi-infos';
import { AreaLink } from './area-link';
import { CapacityCeremonyLinked } from './capacity-ceremony-linked';
import { CategoryCodesLinked } from './category-codes-linked';
import { ContactInfos } from './contact-infos';
import { Detail } from './detail';
import { DishRatesLinked } from './dish-rates-linked';
import { DistanceInfo } from './distance-info';
import { FacilitiesLinked } from './facilities-linked';
import { GpsInfo } from './gps-info';
import { GpsTrack } from './gps-track';
import { ImageGallery } from './image-gallery';
import { LTSTagsLinked } from './ltstags-linked';
import { LicenseInfo } from './license-info';
import { LocationInfoLinked } from './location-info-linked';
import { Metadata } from './metadata';
import { ODHActivityPoiTypesLink } from './odhactivity-poi-types-link';
import { ODHTags } from './odhtags';
import { OperationSchedule } from './operation-schedule';
import { PoiProperty } from './poi-property';
import { Ratings } from './ratings';
import { RelatedContent } from './related-content';
import { Tags } from './tags';
import { VideoItems } from './video-items';
import { Webcam } from './webcam';
/**
 * 
 * @export
 * @interface ODHActivityPoiLinked
 */
export interface ODHActivityPoiLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof ODHActivityPoiLinked
     */
    meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    self?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    odhActive?: boolean;
    /**
     * 
     * @type {Array<ODHTags>}
     * @memberof ODHActivityPoiLinked
     */
    oDHTags?: Array<ODHTags> | null;
    /**
     * 
     * @type {Array<ODHActivityPoiTypesLink>}
     * @memberof ODHActivityPoiLinked
     */
    oDHActivityPoiTypes?: Array<ODHActivityPoiTypesLink> | null;
    /**
     * 
     * @type {Array<AreaLink>}
     * @memberof ODHActivityPoiLinked
     */
    areas?: Array<AreaLink> | null;
    /**
     * 
     * @type {Array<CategoryCodesLinked>}
     * @memberof ODHActivityPoiLinked
     */
    categoryCodes?: Array<CategoryCodesLinked> | null;
    /**
     * 
     * @type {Array<DishRatesLinked>}
     * @memberof ODHActivityPoiLinked
     */
    dishRates?: Array<DishRatesLinked> | null;
    /**
     * 
     * @type {Array<CapacityCeremonyLinked>}
     * @memberof ODHActivityPoiLinked
     */
    capacityCeremony?: Array<CapacityCeremonyLinked> | null;
    /**
     * 
     * @type {Array<FacilitiesLinked>}
     * @memberof ODHActivityPoiLinked
     */
    facilities?: Array<FacilitiesLinked> | null;
    /**
     * 
     * @type {LocationInfoLinked}
     * @memberof ODHActivityPoiLinked
     */
    locationInfo?: LocationInfoLinked;
    /**
     * 
     * @type {Array<LTSTagsLinked>}
     * @memberof ODHActivityPoiLinked
     */
    lTSTags?: Array<LTSTagsLinked> | null;
    /**
     * Id on the primary data Source
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    customId?: string | null;
    /**
     * 
     * @type {Array<Webcam>}
     * @memberof ODHActivityPoiLinked
     */
    webcam?: Array<Webcam> | null;
    /**
     * 
     * @type {{ [key: string]: Array<PoiProperty>; }}
     * @memberof ODHActivityPoiLinked
     */
    poiProperty?: { [key: string]: Array<PoiProperty>; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    poiServices?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    syncSourceInterface?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    syncUpdateMode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    ageFrom?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    ageTo?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    maxSeatingCapacity?: number | null;
    /**
     * 
     * @type {Array<RelatedContent>}
     * @memberof ODHActivityPoiLinked
     */
    relatedContent?: Array<RelatedContent> | null;
    /**
     * 
     * @type {{ [key: string]: Array<AdditionalContact>; }}
     * @memberof ODHActivityPoiLinked
     */
    additionalContact?: { [key: string]: Array<AdditionalContact>; } | null;
    /**
     * generated field
     * @type {{ [key: string]: GpsInfo; }}
     * @memberof ODHActivityPoiLinked
     */
    gpsPoints?: { [key: string]: GpsInfo; } | null;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof ODHActivityPoiLinked
     */
    licenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    outdooractiveID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    outdooractiveElevationID?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    copyrightChecked?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    shortname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    smgId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    highlight?: boolean | null;
    /**
     * Use Ratings.Difficulty
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    difficulty?: string | null;
    /**
     * Use AdditionalPoiInfos.Categories instead
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    type?: string | null;
    /**
     * Use AdditionalPoiInfos.Categories instead
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    subType?: string | null;
    /**
     * Use AdditionalPoiInfos.Categories instead
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    poiType?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ODHActivityPoiLinked
     */
    firstImport?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ODHActivityPoiLinked
     */
    lastChange?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    smgActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    tourismorganizationId?: string | null;
    /**
     * Deprecated use AreaIds
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    areaId?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    areaIds?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    altitudeDifference?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    altitudeHighestPoint?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    altitudeLowestPoint?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    altitudeSumUp?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    altitudeSumDown?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    distanceDuration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    distanceLength?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    isOpen?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    isPrepared?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    runToValley?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    isWithLigth?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    hasRentals?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    hasFreeEntrance?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    liftAvailable?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    feetClimb?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    bikeTransport?: boolean | null;
    /**
     * 
     * @type {Array<OperationSchedule>}
     * @memberof ODHActivityPoiLinked
     */
    operationSchedule?: Array<OperationSchedule> | null;
    /**
     * 
     * @type {Array<GpsInfo>}
     * @memberof ODHActivityPoiLinked
     */
    gpsInfo?: Array<GpsInfo> | null;
    /**
     * 
     * @type {Array<GpsTrack>}
     * @memberof ODHActivityPoiLinked
     */
    gpsTrack?: Array<GpsTrack> | null;
    /**
     * 
     * @type {Array<ImageGallery>}
     * @memberof ODHActivityPoiLinked
     */
    imageGallery?: Array<ImageGallery> | null;
    /**
     * 
     * @type {{ [key: string]: Detail; }}
     * @memberof ODHActivityPoiLinked
     */
    detail?: { [key: string]: Detail; } | null;
    /**
     * 
     * @type {{ [key: string]: ContactInfos; }}
     * @memberof ODHActivityPoiLinked
     */
    contactInfos?: { [key: string]: ContactInfos; } | null;
    /**
     * 
     * @type {{ [key: string]: AdditionalPoiInfos; }}
     * @memberof ODHActivityPoiLinked
     */
    additionalPoiInfos?: { [key: string]: AdditionalPoiInfos; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    smgTags?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    hasLanguage?: Array<string> | null;
    /**
     * 
     * @type {Ratings}
     * @memberof ODHActivityPoiLinked
     */
    ratings?: Ratings;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    exposition?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    ownerRid?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    childPoiIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    masterPoiIds?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    wayNumber?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    number?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    publishedOn?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    source?: string | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof ODHActivityPoiLinked
     */
    mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {DistanceInfo}
     * @memberof ODHActivityPoiLinked
     */
    distanceInfo?: DistanceInfo;
    /**
     * 
     * @type {Array<Tags>}
     * @memberof ODHActivityPoiLinked
     */
    tags?: Array<Tags> | null;
    /**
     * 
     * @type {{ [key: string]: Array<VideoItems>; }}
     * @memberof ODHActivityPoiLinked
     */
    videoItems?: { [key: string]: Array<VideoItems>; } | null;
}
