/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalContact } from './additional-contact';
import { AdditionalPoiInfos } from './additional-poi-infos';
import { AreaLink } from './area-link';
import { CapacityCeremonyLinked } from './capacity-ceremony-linked';
import { CategoryCodesLinked } from './category-codes-linked';
import { ContactInfos } from './contact-infos';
import { Detail } from './detail';
import { DishRatesLinked } from './dish-rates-linked';
import { DistanceInfo } from './distance-info';
import { FacilitiesLinked } from './facilities-linked';
import { GpsInfo } from './gps-info';
import { GpsTrack } from './gps-track';
import { ImageGallery } from './image-gallery';
import { LTSTagsLinked } from './ltstags-linked';
import { LicenseInfo } from './license-info';
import { LocationInfoLinked } from './location-info-linked';
import { Metadata } from './metadata';
import { ODHActivityPoiTypesLink } from './odhactivity-poi-types-link';
import { ODHTags } from './odhtags';
import { OperationSchedule } from './operation-schedule';
import { PoiProperty } from './poi-property';
import { Ratings } from './ratings';
import { RelatedContent } from './related-content';
import { Tags } from './tags';
import { VideoItems } from './video-items';
import { Webcam } from './webcam';
/**
 * 
 * @export
 * @interface ODHActivityPoiLinked
 */
export interface ODHActivityPoiLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof ODHActivityPoiLinked
     */
    Meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    OdhActive?: boolean;
    /**
     * 
     * @type {Array<ODHTags>}
     * @memberof ODHActivityPoiLinked
     */
    ODHTags?: Array<ODHTags> | null;
    /**
     * 
     * @type {Array<ODHActivityPoiTypesLink>}
     * @memberof ODHActivityPoiLinked
     */
    ODHActivityPoiTypes?: Array<ODHActivityPoiTypesLink> | null;
    /**
     * 
     * @type {Array<AreaLink>}
     * @memberof ODHActivityPoiLinked
     */
    Areas?: Array<AreaLink> | null;
    /**
     * 
     * @type {Array<CategoryCodesLinked>}
     * @memberof ODHActivityPoiLinked
     */
    CategoryCodes?: Array<CategoryCodesLinked> | null;
    /**
     * 
     * @type {Array<DishRatesLinked>}
     * @memberof ODHActivityPoiLinked
     */
    DishRates?: Array<DishRatesLinked> | null;
    /**
     * 
     * @type {Array<CapacityCeremonyLinked>}
     * @memberof ODHActivityPoiLinked
     */
    CapacityCeremony?: Array<CapacityCeremonyLinked> | null;
    /**
     * 
     * @type {Array<FacilitiesLinked>}
     * @memberof ODHActivityPoiLinked
     */
    Facilities?: Array<FacilitiesLinked> | null;
    /**
     * 
     * @type {LocationInfoLinked}
     * @memberof ODHActivityPoiLinked
     */
    LocationInfo?: LocationInfoLinked;
    /**
     * 
     * @type {Array<LTSTagsLinked>}
     * @memberof ODHActivityPoiLinked
     */
    LTSTags?: Array<LTSTagsLinked> | null;
    /**
     * Id on the primary data Source
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    CustomId?: string | null;
    /**
     * 
     * @type {Array<Webcam>}
     * @memberof ODHActivityPoiLinked
     */
    Webcam?: Array<Webcam> | null;
    /**
     * 
     * @type {{ [key: string]: Array<PoiProperty>; }}
     * @memberof ODHActivityPoiLinked
     */
    PoiProperty?: { [key: string]: Array<PoiProperty>; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    PoiServices?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    SyncSourceInterface?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    SyncUpdateMode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    AgeFrom?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    AgeTo?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    MaxSeatingCapacity?: number | null;
    /**
     * 
     * @type {Array<RelatedContent>}
     * @memberof ODHActivityPoiLinked
     */
    RelatedContent?: Array<RelatedContent> | null;
    /**
     * 
     * @type {{ [key: string]: Array<AdditionalContact>; }}
     * @memberof ODHActivityPoiLinked
     */
    AdditionalContact?: { [key: string]: Array<AdditionalContact>; } | null;
    /**
     * generated field
     * @type {{ [key: string]: GpsInfo; }}
     * @memberof ODHActivityPoiLinked
     */
    GpsPoints?: { [key: string]: GpsInfo; } | null;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof ODHActivityPoiLinked
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    Id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    OutdooractiveID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    OutdooractiveElevationID?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    CopyrightChecked?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    Active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    Shortname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    SmgId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    Highlight?: boolean | null;
    /**
     * Use Ratings.Difficulty
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    Difficulty?: string | null;
    /**
     * Use AdditionalPoiInfos.Categories instead
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    Type?: string | null;
    /**
     * Use AdditionalPoiInfos.Categories instead
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    SubType?: string | null;
    /**
     * Use AdditionalPoiInfos.Categories instead
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    PoiType?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ODHActivityPoiLinked
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ODHActivityPoiLinked
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    SmgActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    TourismorganizationId?: string | null;
    /**
     * Deprecated use AreaIds
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    AreaId?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    AreaIds?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    AltitudeDifference?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    AltitudeHighestPoint?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    AltitudeLowestPoint?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    AltitudeSumUp?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    AltitudeSumDown?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    DistanceDuration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    DistanceLength?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    IsOpen?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    IsPrepared?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    RunToValley?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    IsWithLigth?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    HasRentals?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    HasFreeEntrance?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    LiftAvailable?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    FeetClimb?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHActivityPoiLinked
     */
    BikeTransport?: boolean | null;
    /**
     * 
     * @type {Array<OperationSchedule>}
     * @memberof ODHActivityPoiLinked
     */
    OperationSchedule?: Array<OperationSchedule> | null;
    /**
     * 
     * @type {Array<GpsInfo>}
     * @memberof ODHActivityPoiLinked
     */
    GpsInfo?: Array<GpsInfo> | null;
    /**
     * 
     * @type {Array<GpsTrack>}
     * @memberof ODHActivityPoiLinked
     */
    GpsTrack?: Array<GpsTrack> | null;
    /**
     * 
     * @type {Array<ImageGallery>}
     * @memberof ODHActivityPoiLinked
     */
    ImageGallery?: Array<ImageGallery> | null;
    /**
     * 
     * @type {{ [key: string]: Detail; }}
     * @memberof ODHActivityPoiLinked
     */
    Detail?: { [key: string]: Detail; } | null;
    /**
     * 
     * @type {{ [key: string]: ContactInfos; }}
     * @memberof ODHActivityPoiLinked
     */
    ContactInfos?: { [key: string]: ContactInfos; } | null;
    /**
     * 
     * @type {{ [key: string]: AdditionalPoiInfos; }}
     * @memberof ODHActivityPoiLinked
     */
    AdditionalPoiInfos?: { [key: string]: AdditionalPoiInfos; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    SmgTags?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    HasLanguage?: Array<string> | null;
    /**
     * 
     * @type {Ratings}
     * @memberof ODHActivityPoiLinked
     */
    Ratings?: Ratings;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    Exposition?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    OwnerRid?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    ChildPoiIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    MasterPoiIds?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof ODHActivityPoiLinked
     */
    WayNumber?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    Number?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHActivityPoiLinked
     */
    PublishedOn?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ODHActivityPoiLinked
     */
    Source?: string | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof ODHActivityPoiLinked
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {DistanceInfo}
     * @memberof ODHActivityPoiLinked
     */
    DistanceInfo?: DistanceInfo;
    /**
     * 
     * @type {Array<Tags>}
     * @memberof ODHActivityPoiLinked
     */
    Tags?: Array<Tags> | null;
    /**
     * 
     * @type {{ [key: string]: Array<VideoItems>; }}
     * @memberof ODHActivityPoiLinked
     */
    VideoItems?: { [key: string]: Array<VideoItems>; } | null;
}
