/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LTSTaggingInfo } from './ltstagging-info';
import { LicenseInfo } from './license-info';
import { Metadata } from './metadata';
/**
 * 
 * @export
 * @interface ODHTagLinked
 */
export interface ODHTagLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof ODHTagLinked
     */
    Meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof ODHTagLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof ODHTagLinked
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof ODHTagLinked
     */
    Id?: string | null;
    /**
     * Deprecated, refer to TagName
     * @type {string}
     * @memberof ODHTagLinked
     */
    Shortname?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ODHTagLinked
     */
    TagName?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHTagLinked
     */
    ValidForEntity?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHTagLinked
     */
    Source?: Array<string> | null;
    /**
     * 
     * @type {Date}
     * @memberof ODHTagLinked
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ODHTagLinked
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ODHTagLinked
     */
    DisplayAsCategory?: boolean | null;
    /**
     * Deprecated, use Mapping or MappedIds
     * @type {{ [key: string]: string; }}
     * @memberof ODHTagLinked
     */
    IDMCategoryMapping?: { [key: string]: string; } | null;
    /**
     * 
     * @type {LTSTaggingInfo}
     * @memberof ODHTagLinked
     */
    LTSTaggingInfo?: LTSTaggingInfo;
    /**
     * Deprecated, use ValidForEntity
     * @type {string}
     * @memberof ODHTagLinked
     */
    MainEntity?: string | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof ODHTagLinked
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHTagLinked
     */
    MappedTagIds?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof ODHTagLinked
     */
    PublishDataWithTagOn?: { [key: string]: boolean; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ODHTagLinked
     */
    PublishedOn?: Array<string> | null;
}
