/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OperationScheduleTime
 */
export interface OperationScheduleTime {
    /**
     * 
     * @type {string}
     * @memberof OperationScheduleTime
     */
    start?: string;
    /**
     * 
     * @type {string}
     * @memberof OperationScheduleTime
     */
    end?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OperationScheduleTime
     */
    monday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OperationScheduleTime
     */
    tuesday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OperationScheduleTime
     */
    wednesday?: boolean;
    /**
     * Will be removed within 2023-12-31
     * @type {boolean}
     * @memberof OperationScheduleTime
     */
    thuresday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OperationScheduleTime
     */
    thursday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OperationScheduleTime
     */
    friday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OperationScheduleTime
     */
    saturday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OperationScheduleTime
     */
    sunday?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OperationScheduleTime
     */
    state?: number;
    /**
     * 
     * @type {number}
     * @memberof OperationScheduleTime
     */
    timecode?: number;
}
