/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OperationScheduleTime } from './operation-schedule-time';
/**
 * Wiki Article on <a href='https://github.com/noi-techpark/odh-docs/wiki/Operationschedule-Format' target='_blank'>Wiki Article</a>
 * @export
 * @interface OperationSchedule
 */
export interface OperationSchedule {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof OperationSchedule
     */
    OperationscheduleName?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Date}
     * @memberof OperationSchedule
     */
    Start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OperationSchedule
     */
    Stop?: Date;
    /**
     * 1 - Standard, 2 - Only day + month recurring (year not to consider) 3 - only month recurring (season: year and day not to consider), Wiki Article on <a href='https://github.com/noi-techpark/odh-docs/wiki/Operationschedule-Format' target='_blank'>Wiki Article</a>
     * @type {string}
     * @memberof OperationSchedule
     */
    Type?: string | null;
    /**
     * 
     * @type {Array<OperationScheduleTime>}
     * @memberof OperationSchedule
     */
    OperationScheduleTime?: Array<OperationScheduleTime> | null;
}
