/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Bank } from './bank';
/**
 * 
 * @export
 * @interface PaymentTerm
 */
export interface PaymentTerm {
    /**
     * 
     * @type {string}
     * @memberof PaymentTerm
     */
    Id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentTerm
     */
    Methods?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentTerm
     */
    Prepayment?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentTerm
     */
    Ccards?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentTerm
     */
    Priority?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentTerm
     */
    Description?: string | null;
    /**
     * 
     * @type {Bank}
     * @memberof PaymentTerm
     */
    Bank?: Bank;
}
