/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PGCRUDResult
 */
export interface PGCRUDResult {
    /**
     * 
     * @type {string}
     * @memberof PGCRUDResult
     */
    Id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PGCRUDResult
     */
    Operation?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PGCRUDResult
     */
    Updated?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PGCRUDResult
     */
    Created?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PGCRUDResult
     */
    Deleted?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PGCRUDResult
     */
    Error?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PGCRUDResult
     */
    Compareobject?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof PGCRUDResult
     */
    Objectchanged?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PGCRUDResult
     */
    Objectimageschanged?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PGCRUDResult
     */
    Pushchannels?: Array<string> | null;
    /**
     * 
     * @type {any}
     * @memberof PGCRUDResult
     */
    Changes?: any | null;
}
