/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LicenseInfo } from './license-info';
import { Metadata } from './metadata';
/**
 * 
 * @export
 * @interface PublisherLinked
 */
export interface PublisherLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof PublisherLinked
     */
    Meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof PublisherLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof PublisherLinked
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof PublisherLinked
     */
    Id?: string | null;
    /**
     * Deprecated, refer to Name
     * @type {string}
     * @memberof PublisherLinked
     */
    Shortname?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PublisherLinked
     */
    Name?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Date}
     * @memberof PublisherLinked
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PublisherLinked
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PublisherLinked
     */
    PublisherUrl?: string | null;
}
