/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ratings
 */
export interface Ratings {
    /**
     * 
     * @type {string}
     * @memberof Ratings
     */
    stamina?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Ratings
     */
    experience?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Ratings
     */
    landscape?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Ratings
     */
    difficulty?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Ratings
     */
    technique?: string | null;
}
