/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RealTimeMeasurements
 */
export interface RealTimeMeasurements {
    /**
     * 
     * @type {string}
     * @memberof RealTimeMeasurements
     */
    Code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RealTimeMeasurements
     */
    Description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RealTimeMeasurements
     */
    ImageUrl?: string | null;
}
