/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AreaLink } from './area-link';
import { ContactInfos } from './contact-infos';
import { Detail } from './detail';
import { DistanceInfo } from './distance-info';
import { GpsInfo } from './gps-info';
import { GpsPolygon } from './gps-polygon';
import { ImageGallery } from './image-gallery';
import { LicenseInfo } from './license-info';
import { LocationInfoLinked } from './location-info-linked';
import { Metadata } from './metadata';
import { ODHTags } from './odhtags';
import { OperationSchedule } from './operation-schedule';
import { RegionLink } from './region-link';
import { RelatedContent } from './related-content';
import { SkiRegionLink } from './ski-region-link';
import { TourismAssociationLink } from './tourism-association-link';
import { Webcam } from './webcam';
/**
 * 
 * @export
 * @interface SkiAreaLinked
 */
export interface SkiAreaLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof SkiAreaLinked
     */
    Meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    Self?: string | null;
    /**
     * 
     * @type {Array<ODHTags>}
     * @memberof SkiAreaLinked
     */
    ODHTags?: Array<ODHTags> | null;
    /**
     * 
     * @type {boolean}
     * @memberof SkiAreaLinked
     */
    OdhActive?: boolean;
    /**
     * 
     * @type {SkiRegionLink}
     * @memberof SkiAreaLinked
     */
    SkiRegion?: SkiRegionLink;
    /**
     * 
     * @type {Array<AreaLink>}
     * @memberof SkiAreaLinked
     */
    Areas?: Array<AreaLink> | null;
    /**
     * 
     * @type {Array<TourismAssociationLink>}
     * @memberof SkiAreaLinked
     */
    TourismAssociations?: Array<TourismAssociationLink> | null;
    /**
     * 
     * @type {Array<RegionLink>}
     * @memberof SkiAreaLinked
     */
    Regions?: Array<RegionLink> | null;
    /**
     * 
     * @type {LocationInfoLinked}
     * @memberof SkiAreaLinked
     */
    LocationInfo?: LocationInfoLinked;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    SkiRegionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    SkiAreaMapURL?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    TotalSlopeKm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    SlopeKmBlue?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    SlopeKmRed?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    SlopeKmBlack?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    LiftCount?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SkiAreaLinked
     */
    AltitudeFrom?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SkiAreaLinked
     */
    AltitudeTo?: number | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SkiAreaLinked
     */
    SkiRegionName?: { [key: string]: string; } | null;
    /**
     * Deprecated use AreaIds
     * @type {Array<string>}
     * @memberof SkiAreaLinked
     */
    AreaId?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiAreaLinked
     */
    AreaIds?: Array<string> | null;
    /**
     * 
     * @type {Array<Webcam>}
     * @memberof SkiAreaLinked
     */
    Webcam?: Array<Webcam> | null;
    /**
     * 
     * @type {Array<OperationSchedule>}
     * @memberof SkiAreaLinked
     */
    OperationSchedule?: Array<OperationSchedule> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiAreaLinked
     */
    TourismvereinIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiAreaLinked
     */
    RegionIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiAreaLinked
     */
    MunicipalityIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiAreaLinked
     */
    DistrictIds?: Array<string> | null;
    /**
     * 
     * @type {Array<GpsPolygon>}
     * @memberof SkiAreaLinked
     */
    GpsPolygon?: Array<GpsPolygon> | null;
    /**
     * 
     * @type {Array<RelatedContent>}
     * @memberof SkiAreaLinked
     */
    RelatedContent?: Array<RelatedContent> | null;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof SkiAreaLinked
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    Id?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SkiAreaLinked
     */
    Active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    CustomId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    Shortname?: string | null;
    /**
     * Deprecated, use GpsPoints
     * @type {string}
     * @memberof SkiAreaLinked
     */
    Gpstype?: string | null;
    /**
     * Deprecated, use GpsPoints
     * @type {number}
     * @memberof SkiAreaLinked
     */
    Latitude?: number;
    /**
     * Deprecated, use GpsPoints
     * @type {number}
     * @memberof SkiAreaLinked
     */
    Longitude?: number;
    /**
     * Deprecated, use GpsPoints
     * @type {number}
     * @memberof SkiAreaLinked
     */
    Altitude?: number | null;
    /**
     * Deprecated, use GpsPoints
     * @type {string}
     * @memberof SkiAreaLinked
     */
    AltitudeUnitofMeasure?: string | null;
    /**
     * 
     * @type {{ [key: string]: Detail; }}
     * @memberof SkiAreaLinked
     */
    Detail?: { [key: string]: Detail; } | null;
    /**
     * 
     * @type {{ [key: string]: ContactInfos; }}
     * @memberof SkiAreaLinked
     */
    ContactInfos?: { [key: string]: ContactInfos; } | null;
    /**
     * 
     * @type {Array<ImageGallery>}
     * @memberof SkiAreaLinked
     */
    ImageGallery?: Array<ImageGallery> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiAreaLinked
     */
    SmgTags?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof SkiAreaLinked
     */
    SmgActive?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiAreaLinked
     */
    HasLanguage?: Array<string> | null;
    /**
     * 
     * @type {Date}
     * @memberof SkiAreaLinked
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SkiAreaLinked
     */
    FirstImport?: Date | null;
    /**
     * generated field
     * @type {{ [key: string]: GpsInfo; }}
     * @memberof SkiAreaLinked
     */
    GpsPoints?: { [key: string]: GpsInfo; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiAreaLinked
     */
    PublishedOn?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof SkiAreaLinked
     */
    Source?: string | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof SkiAreaLinked
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {DistanceInfo}
     * @memberof SkiAreaLinked
     */
    DistanceInfo?: DistanceInfo;
}
