/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContactInfos } from './contact-infos';
import { Detail } from './detail';
import { DistanceInfo } from './distance-info';
import { GpsInfo } from './gps-info';
import { GpsPolygon } from './gps-polygon';
import { ImageGallery } from './image-gallery';
import { LicenseInfo } from './license-info';
import { Metadata } from './metadata';
import { ODHTags } from './odhtags';
import { RelatedContent } from './related-content';
import { Webcam } from './webcam';
/**
 * 
 * @export
 * @interface SkiRegionLinked
 */
export interface SkiRegionLinked {
    /**
     * 
     * @type {Metadata}
     * @memberof SkiRegionLinked
     */
    meta?: Metadata;
    /**
     * 
     * @type {string}
     * @memberof SkiRegionLinked
     */
    self?: string | null;
    /**
     * 
     * @type {Array<ODHTags>}
     * @memberof SkiRegionLinked
     */
    oDHTags?: Array<ODHTags> | null;
    /**
     * 
     * @type {boolean}
     * @memberof SkiRegionLinked
     */
    odhActive?: boolean;
    /**
     * 
     * @type {Array<GpsPolygon>}
     * @memberof SkiRegionLinked
     */
    gpsPolygon?: Array<GpsPolygon> | null;
    /**
     * 
     * @type {Array<Webcam>}
     * @memberof SkiRegionLinked
     */
    webcam?: Array<Webcam> | null;
    /**
     * 
     * @type {Array<RelatedContent>}
     * @memberof SkiRegionLinked
     */
    relatedContent?: Array<RelatedContent> | null;
    /**
     * 
     * @type {LicenseInfo}
     * @memberof SkiRegionLinked
     */
    licenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof SkiRegionLinked
     */
    id?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SkiRegionLinked
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SkiRegionLinked
     */
    customId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SkiRegionLinked
     */
    shortname?: string | null;
    /**
     * Deprecated, use GpsPoints
     * @type {string}
     * @memberof SkiRegionLinked
     */
    gpstype?: string | null;
    /**
     * Deprecated, use GpsPoints
     * @type {number}
     * @memberof SkiRegionLinked
     */
    latitude?: number;
    /**
     * Deprecated, use GpsPoints
     * @type {number}
     * @memberof SkiRegionLinked
     */
    longitude?: number;
    /**
     * Deprecated, use GpsPoints
     * @type {number}
     * @memberof SkiRegionLinked
     */
    altitude?: number | null;
    /**
     * Deprecated, use GpsPoints
     * @type {string}
     * @memberof SkiRegionLinked
     */
    altitudeUnitofMeasure?: string | null;
    /**
     * 
     * @type {{ [key: string]: Detail; }}
     * @memberof SkiRegionLinked
     */
    detail?: { [key: string]: Detail; } | null;
    /**
     * 
     * @type {{ [key: string]: ContactInfos; }}
     * @memberof SkiRegionLinked
     */
    contactInfos?: { [key: string]: ContactInfos; } | null;
    /**
     * 
     * @type {Array<ImageGallery>}
     * @memberof SkiRegionLinked
     */
    imageGallery?: Array<ImageGallery> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiRegionLinked
     */
    smgTags?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof SkiRegionLinked
     */
    smgActive?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiRegionLinked
     */
    hasLanguage?: Array<string> | null;
    /**
     * 
     * @type {Date}
     * @memberof SkiRegionLinked
     */
    lastChange?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SkiRegionLinked
     */
    firstImport?: Date | null;
    /**
     * generated field
     * @type {{ [key: string]: GpsInfo; }}
     * @memberof SkiRegionLinked
     */
    gpsPoints?: { [key: string]: GpsInfo; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkiRegionLinked
     */
    publishedOn?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof SkiRegionLinked
     */
    source?: string | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof SkiRegionLinked
     */
    mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {DistanceInfo}
     * @memberof SkiRegionLinked
     */
    distanceInfo?: DistanceInfo;
}
