/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MeasuringpointReduced } from './measuringpoint-reduced';
/**
 * 
 * @export
 * @interface SnowReportBaseData
 */
export interface SnowReportBaseData {
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    RID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    skiregion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    areaname?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SnowReportBaseData
     */
    lastUpdate?: Date;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    lang?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    skiAreaSlopeKm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    skiMapUrl?: string | null;
    /**
     * 
     * @type {Array<MeasuringpointReduced>}
     * @memberof SnowReportBaseData
     */
    measuringpoints?: Array<MeasuringpointReduced> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SnowReportBaseData
     */
    webcamUrl?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalskilift?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    openskilift?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalskiliftkm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    openskiliftkm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalskislopes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    openskislopes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalskislopeskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    openskislopeskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totaltracks?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    opentracks?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totaltrackskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    opentrackskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalslides?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    opentslides?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totalslideskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    opentslideskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    totaliceskating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    openiceskating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactadress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contacttel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactcap?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactcity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactfax?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactweburl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactlogo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactgpsnorth?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    contactgpseast?: string | null;
}
