/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MeasuringpointReduced } from './measuringpoint-reduced';
/**
 * 
 * @export
 * @interface SnowReportBaseData
 */
export interface SnowReportBaseData {
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    RID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Skiregion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Areaname?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SnowReportBaseData
     */
    LastUpdate?: Date;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Lang?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    SkiAreaSlopeKm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    SkiMapUrl?: string | null;
    /**
     * 
     * @type {Array<MeasuringpointReduced>}
     * @memberof SnowReportBaseData
     */
    Measuringpoints?: Array<MeasuringpointReduced> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SnowReportBaseData
     */
    WebcamUrl?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Totalskilift?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Openskilift?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Totalskiliftkm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Openskiliftkm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Totalskislopes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Openskislopes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Totalskislopeskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Openskislopeskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Totaltracks?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Opentracks?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Totaltrackskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Opentrackskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Totalslides?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Opentslides?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Totalslideskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Opentslideskm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Totaliceskating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Openiceskating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Contactadress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Contacttel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Contactcap?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Contactcity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Contactfax?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Contactweburl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Contactmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Contactlogo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Contactgpsnorth?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnowReportBaseData
     */
    Contactgpseast?: string | null;
}
