/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Stationdata
 */
export interface Stationdata {
    /**
     * 
     * @type {Date}
     * @memberof Stationdata
     */
    Date?: Date;
    /**
     * 
     * @type {number}
     * @memberof Stationdata
     */
    Id?: number;
    /**
     * 
     * @type {string}
     * @memberof Stationdata
     */
    CityName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Stationdata
     */
    WeatherCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Stationdata
     */
    WeatherDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Stationdata
     */
    WeatherImgUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Stationdata
     */
    MinTemp?: number;
    /**
     * 
     * @type {number}
     * @memberof Stationdata
     */
    Maxtemp?: number;
    /**
     * 
     * @type {number}
     * @memberof Stationdata
     */
    MaxTemp?: number;
}
