/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ImageGallery } from './image-gallery';
import { Metadata } from './metadata';
/**
 * 
 * @export
 * @interface TourismMetaData
 */
export interface TourismMetaData {
    /**
     * 
     * @type {Array<string>}
     * @memberof TourismMetaData
     */
    ApiFilter?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof TourismMetaData
     */
    Id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourismMetaData
     */
    OdhType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourismMetaData
     */
    SwaggerUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourismMetaData
     */
    Self?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourismMetaData
     */
    ApiUrl?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TourismMetaData
     */
    PathParam: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TourismMetaData
     */
    BaseUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TourismMetaData
     */
    Deprecated?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TourismMetaData
     */
    SingleDataset?: boolean;
    /**
     * 
     * @type {Metadata}
     * @memberof TourismMetaData
     */
    Meta?: Metadata;
    /**
     * 
     * @type {Date}
     * @memberof TourismMetaData
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TourismMetaData
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TourismMetaData
     */
    Shortname: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TourismMetaData
     */
    Sources?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof TourismMetaData
     */
    RecordCount?: { [key: string]: number; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof TourismMetaData
     */
    Output?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof TourismMetaData
     */
    ApiDescription?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TourismMetaData
     */
    PublishedOn?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof TourismMetaData
     */
    ApiAccess?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<ImageGallery>}
     * @memberof TourismMetaData
     */
    ImageGallery?: Array<ImageGallery> | null;
}
