/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StringStringValuesKeyValuePair } from './string-string-values-key-value-pair';
/**
 * 
 * @export
 * @interface V1FileUploadBody
 */
export interface V1FileUploadBody {
    /**
     * 
     * @type {Array<StringStringValuesKeyValuePair>}
     * @memberof V1FileUploadBody
     */
    Form?: Array<StringStringValuesKeyValuePair>;
}
