/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VideoItems
 */
export interface VideoItems {
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    Name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    Url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    VideoSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    VideoType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    StreamingSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    VideoTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    VideoDesc?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof VideoItems
     */
    Active?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    CopyRight?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    License?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    LicenseHolder?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    Language?: string | null;
}
