/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VideoItems
 */
export interface VideoItems {
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    videoSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    videoType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    streamingSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    videoTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    videoDesc?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof VideoItems
     */
    active?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    copyRight?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    license?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    licenseHolder?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoItems
     */
    language?: string | null;
}
