/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WeatherObservation
 */
export interface WeatherObservation {
    /**
     * 
     * @type {string}
     * @memberof WeatherObservation
     */
    Id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WeatherObservation
     */
    Level?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WeatherObservation
     */
    LevelId?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof WeatherObservation
     */
    WeatherStatus?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof WeatherObservation
     */
    IconID?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof WeatherObservation
     */
    Date?: Date | null;
}
