/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GpsInfo } from './gps-info';
import { LicenseInfo } from './license-info';
import { PublishedonObject } from './publishedon-object';
/**
 * 
 * @export
 * @interface WebcamInfo
 */
export interface WebcamInfo {
    /**
     * 
     * @type {LicenseInfo}
     * @memberof WebcamInfo
     */
    LicenseInfo?: LicenseInfo;
    /**
     * 
     * @type {string}
     * @memberof WebcamInfo
     */
    Id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WebcamInfo
     */
    Streamurl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WebcamInfo
     */
    Previewurl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof WebcamInfo
     */
    LastChange?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof WebcamInfo
     */
    FirstImport?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof WebcamInfo
     */
    Shortname?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof WebcamInfo
     */
    Active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WebcamInfo
     */
    SmgActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WebcamInfo
     */
    Source?: string | null;
    /**
     * 
     * @type {Array<PublishedonObject>}
     * @memberof WebcamInfo
     */
    WebcamAssignedOn?: Array<PublishedonObject> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebcamInfo
     */
    AreaIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebcamInfo
     */
    SmgTags?: Array<string> | null;
    /**
     * generated field
     * @type {{ [key: string]: GpsInfo; }}
     * @memberof WebcamInfo
     */
    GpsPoints?: { [key: string]: GpsInfo; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebcamInfo
     */
    PublishedOn?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof WebcamInfo
     */
    Mapping?: { [key: string]: { [key: string]: string; }; } | null;
    /**
     * 
     * @type {Array<GpsInfo>}
     * @memberof WebcamInfo
     */
    GpsInfos?: Array<GpsInfo> | null;
    /**
     * 
     * @type {string}
     * @memberof WebcamInfo
     */
    WebcamId?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof WebcamInfo
     */
    Webcamname?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof WebcamInfo
     */
    Webcamurl?: string | null;
    /**
     * 
     * @type {GpsInfo}
     * @memberof WebcamInfo
     */
    GpsInfo?: GpsInfo;
    /**
     * 
     * @type {number}
     * @memberof WebcamInfo
     */
    ListPosition?: number | null;
}
