/* tslint:disable */
/* eslint-disable */
/**
 * Open Data Hub Tourism Api
 * Open Data Hub Tourism Api based on .Net Core with PostgreSQL
 *
 * OpenAPI spec version: v1
 * Contact: help@opendatahub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GpsInfo } from './gps-info';
/**
 * 
 * @export
 * @interface Webcam
 */
export interface Webcam {
    /**
     * 
     * @type {string}
     * @memberof Webcam
     */
    webcamId?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Webcam
     */
    webcamname?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof Webcam
     */
    webcamurl?: string | null;
    /**
     * 
     * @type {GpsInfo}
     * @memberof Webcam
     */
    gpsInfo?: GpsInfo;
    /**
     * 
     * @type {number}
     * @memberof Webcam
     */
    listPosition?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Webcam
     */
    streamurl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Webcam
     */
    previewurl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Webcam
     */
    source?: string | null;
}
